### ISSUE TITLE
1.18.2 backport?

### ISSUE THREAD

**Issue by ConqAra** [NerjalNosk/bettermaps#3]
This is an issue I really wanted for my modpack, it's the only real annoying issue I have left when people on the server open a chest with something like a woodland mansion map in it. Is a backport possible?

**Comment by NerjalNosk** [comment]
Honestly, I haven't been considering working on 1.18 in a long time now. But I guess I might come around to doing it, when I get the time

**Comment by NerjalNosk** [comment]
Released in [0.5.1+1.18](https://modrinth.com/mod/bettermaps/version/0.5.1+1.18.2)
